import os
from xhtml2pdf import pisa
import markdown

def convert_md_to_pdf(md_path, pdf_name):
    if not os.path.exists(md_path):
        print(f"Error: {md_path} not found.")
        return

    with open(md_path, "r", encoding="utf-8") as f:
        md_text = f.read()

    # Premium CSS styling for academic guides
    css = """
    @page {
        size: A4;
        margin: 2cm;
    }
    body { 
        font-family: Helvetica, Arial, sans-serif; 
        font-size: 11pt; 
        line-height: 1.5; 
        color: #333;
    }
    h1 { 
        color: #1a2a6c; 
        text-align: center; 
        font-size: 24pt;
        border-bottom: 3px solid #b21f1f; 
        padding-bottom: 10px;
        margin-bottom: 30px;
    }
    h2 { 
        color: #b21f1f; 
        font-size: 18pt;
        border-bottom: 1px solid #ccc; 
        margin-top: 25px;
        padding-bottom: 5px;
    }
    h3 { 
        color: #fdbb2d; 
        font-size: 14pt;
        margin-top: 20px; 
        background-color: #f8f8f8;
        padding: 5px;
    }
    p { margin-bottom: 12px; }
    ul, ol { margin-bottom: 15px; }
    li { margin-bottom: 6px; }
    table { 
        width: 100%; 
        border-collapse: collapse; 
        margin-top: 15px; 
        margin-bottom: 15px; 
    }
    th, td { 
        border: 1px solid #ddd; 
        padding: 12px; 
        text-align: left; 
    }
    th { 
        background-color: #1a2a6c; 
        color: white;
    }
    tr:nth-child(even) {
        background-color: #f9f9f9;
    }
    strong { color: #b21f1f; }
    .footer {
        position: fixed;
        bottom: 0;
        width: 100%;
        text-align: center;
        font-size: 9pt;
        color: #777;
        border-top: 1px solid #eee;
        padding-top: 5px;
    }
    """

    html_body = markdown.markdown(md_text, extensions=['tables', 'fenced_code'])

    full_html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <style>{css}</style>
    </head>
    <body>
        {html_body}
        <div class="footer">Generated by Dr. Abebe's EUEE Prep Bot</div>
    </body>
    </html>
    """

    with open(pdf_name, "w+b") as out:
        pisa_status = pisa.CreatePDF(full_html, dest=out)
        
    if not pisa_status.err:
        print(f"DONE: PDF generated successfully: {pdf_name}")
    else:
        print(f"ERROR: Error generating PDF: {pdf_name}")

if __name__ == "__main__":
    # Define tasks
    tasks = [
        (r"euee_notes\english\notes.md", "Dr_Abebe_English_Ultimate_Guide.pdf"),
        (r"euee_notes\economics\notes.md", "Dr_Abebe_Economics_Ultimate_Guide.pdf")
    ]

    for md_path, pdf_name in tasks:
        convert_md_to_pdf(md_path, pdf_name)
