
import os
import markdown
from xhtml2pdf import pisa
from datetime import datetime

def generate_personalized_review_pdf(user_id, name, wrong_questions, lang="en"):
    """
    Generates a PDF review sheet containing questions the user got wrong.
    """
    if not wrong_questions:
        return None

    title = "Your Personalized EUEE Review Sheet" if lang == "en" else "የግል የ EUEE ክለሳ ማስታወሻዎ"
    date_str = datetime.now().strftime("%B %d, %Y")
    
    md_lines = [
        f"# {title}",
        f"**Student:** {name} | **Date:** {date_str}",
        "\n---\n",
        "This document contains questions you recently missed. Study the explanations carefully to ensure you master these concepts before the exam.\n" if lang == "en" else "ይህ ሰነድ በቅርቡ የተሳሳቱትን ጥያቄዎች ይዟል። ከፈተናው በፊት እነዚህን ፅንሰ-ሀሳቦች ጠንቅቀው ማወቅዎን ለማረጋገጥ ማብራሪያዎቹን በጥንቃቄ ያጥኑ።\n"
    ]

    for i, q in enumerate(wrong_questions, 1):
        subject = q.get("subject", "General").title()
        topic = q.get("topic", "General")
        question_text = q.get("question", "")
        options = q.get("options", {})
        correct_answer = q.get("answer", "")
        explanation = q.get("explanation", "No explanation available.")
        
        md_lines.append(f"## {i}. {subject} - {topic}")
        md_lines.append(f"**Question:** {question_text}")
        
        for opt_key in sorted(options.keys()):
            md_lines.append(f"- **{opt_key}:** {options[opt_key]}")
            
        md_lines.append(f"\n**✅ Correct Answer:** {correct_answer}")
        md_lines.append(f"**💡 Explanation:** {explanation}")
        md_lines.append("\n---\n")

    md_text = "\n".join(md_lines)
    
    # CSS for premium look
    css = """
    body { font-family: Helvetica, Arial, sans-serif; font-size: 11pt; line-height: 1.5; color: #333; }
    h1 { color: #2C3E50; text-align: center; border-bottom: 2px solid #34495E; padding-bottom: 10px; }
    h2 { color: #2980B9; border-bottom: 1px solid #BDC3C7; margin-top: 25px; padding-bottom: 5px; }
    p { margin-bottom: 10px; }
    li { margin-bottom: 5px; }
    strong { color: #C0392B; }
    .footer { text-align: center; font-size: 9pt; color: #7F8C8D; margin-top: 30px; border-top: 1px solid #BDC3C7; padding-top: 10px; }
    """
    
    html_body = markdown.markdown(md_text)
    full_html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <style>{css}</style>
    </head>
    <body>
        {html_body}
        <div class="footer">Generated by EUEE Abebe Bot — Your AI Study Companion</div>
    </body>
    </html>
    """
    
    filename = f"Review_Sheet_{user_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    output_path = os.path.join("temp_pdfs", filename)
    
    if not os.path.exists("temp_pdfs"):
        os.makedirs("temp_pdfs")
        
    with open(output_path, "w+b") as out:
        pisa_status = pisa.CreatePDF(full_html, dest=out)
        
    return output_path if pisa_status.err == 0 else None
